# The lab's job is to be usable immediately after `apply`, so it emits the two
# things needed next: how to reach it, and an inventory Ansible can consume.

output "machines" {
  description = "Lab machines, their roles and their addresses inside the lab network."
  value = {
    for name, m in local.machines : name => {
      role  = m.role
      ip    = m.ip
      fqdn  = "${name}.${var.lab_domain}"
      vm_id = var.vmid_base + m.vmid_offset
      # What the guest agent reports, which is not always what was asked for —
      # and when they differ, that difference is the finding.
      reported = try(proxmox_virtual_environment_vm.lab[name].ipv4_addresses, [])
    }
  }
}

output "gateway_uplink_address" {
  description = <<-EOT
    Address the gateway picked up on the uplink. This is the only way into the
    lab: everything else is reachable through it and from nowhere else.
  EOT
  value = try(
    [for addrs in proxmox_virtual_environment_vm.lab["gateway"].ipv4_addresses :
      [for a in addrs : a if a != "127.0.0.1" && !startswith(a, split(".", local.gateway_ip)[0])]
    ][0][0],
    "pending — the guest agent has not reported yet, try `terraform refresh`"
  )
}

output "ssh_config" {
  description = "Drop-in SSH configuration reaching the lab through the gateway. Write it to a file and use `ssh -F`."
  value = <<-EOT
    # Managed Linux reference architecture — lab access.
    #
    # Only the gateway is reachable directly. Everything else is proxied
    # through it, which is not a convenience: it is the lab demonstrating the
    # isolation it is supposed to have.

    Host lab-gateway
      HostName ${try(
  [for addrs in proxmox_virtual_environment_vm.lab["gateway"].ipv4_addresses :
    [for a in addrs : a if a != "127.0.0.1" && !startswith(a, split(".", local.gateway_ip)[0])]
  ][0][0],
"GATEWAY-ADDRESS-PENDING")}
      User ${var.admin_username}

    %{for name, m in local.machines~}
    %{if name != "gateway"~}
    Host lab-${name}
      HostName ${m.ip}
      User ${var.admin_username}
      ProxyJump lab-gateway
    %{endif~}
    %{endfor~}
  EOT
}

output "ansible_inventory" {
  description = "Inventory for the playbooks under ../ansible/. Written to inventory.ini by `make inventory`."
  value = <<-EOT
    # Generated by terraform. Do not edit — `make inventory` overwrites it.
    #
    # Group names match role names so that `--limit <role> --tags <role>` works,
    # which is the convention the playbooks assume.

    [gateway]
    %{for name, m in local.machines~}
    %{if m.role == "gateway"~}
    ${name} ansible_host=${m.ip}
    %{endif~}
    %{endfor~}

    [idp]
    %{for name, m in local.machines~}
    %{if m.role == "idp"~}
    ${name} ansible_host=${m.ip}
    %{endif~}
    %{endfor~}

    [servers]
    %{for name, m in local.machines~}
    %{if m.role == "server"~}
    ${name} ansible_host=${m.ip}
    %{endif~}
    %{endfor~}

    [desktops]
    %{for name, m in local.machines~}
    %{if m.role == "desktop"~}
    ${name} ansible_host=${m.ip}
    %{endif~}
    %{endfor~}

    [lab:children]
    gateway
    behind_gateway

    # Everything that is reached *through* the gateway. The gateway itself must
    # not be in here: giving it a ProxyJump to itself produces a connection
    # that hangs rather than fails, which costs an afternoon the first time.
    [behind_gateway:children]
    idp
    servers
    desktops

    [lab:vars]
    ansible_user=${var.admin_username}
    ansible_python_interpreter=/usr/bin/python3

    [behind_gateway:vars]
    ansible_ssh_common_args='-o ProxyJump=${var.admin_username}@${try(
  [for addrs in proxmox_virtual_environment_vm.lab["gateway"].ipv4_addresses :
    [for a in addrs : a if a != "127.0.0.1" && !startswith(a, split(".", local.gateway_ip)[0])]
  ][0][0],
"GATEWAY-ADDRESS-PENDING")}'
  EOT
}
